---
title: Bookmarks and Diaries
author: Jiwan Heo
date: '2020-08-31'
tags:
  - bookmarks
  - webdev
thumbnail: "featured.jpg"
thumbnailby: "@mohammadfathollahi"
---
# 2024 Feb

Wow it's been almost 4 years since I wrote this. A lot happened since last time,
we're no longer in COVID lockdown, have a new job, I live in Mexico now. It 
kinda feels like yesterday when I started this blog post series, can't believe
so much time has passed!

I've definitely grown personally and technically. I think I'm more relaxed now,
I still feel like a child who doesn't know anything, but I do have more 
tranquility that I didn't have before. Coding stuff-wise, I definitely don't 
know everything, but I do consider myself an expert in R & shiny (hesistant to 
say web dev, because it's so big). 

Recently, I've been taking interest in learning more about the context in which
I work out of. I got the Comptia Network+, while I studied computer networking, 
and I'm learning Go now, to see what's possible to build with this, I don't 
exactly know what I want to do with it, but I think it'll help me with building 
cloud/server type stuff more easily.

I'm attending my first conference ever at the end of this month for PHUSE 
Connect. I'll be presenting about data visualization strategy in the pharma 
industry. Super excited, but also a little nervous, b/c it'll be my first time 
public speaking outside school!

The biggest theme in my life right now is the whole travelling while working 
thing. It has always been a goal of mine, and I'm so happy and grateful to have 
experienced this! Obviously, there are downsides to this too, just like any 
other things in life, like not being able to spend quality time with family and 
friends that I already have back home. Not sure if "guilty" is the right word, 
but the more time I want to spend here, the more actively I'm making the 
decision to not be there, and it feels a little weird.

But all that to say, I really like where I am in my life right now. I still 
love learning new things, (a big life/career goal of mine) and I love widening 
my world view. Let's see what happens next!

Cheers!

# 2020 August

For someone who's learning CSS, I should really start styling this blog.

- https://www.youtube.com/watch?v=sppSnBQVt0k&list=WL&index=11&t=4774s Where it all started
- https://github.com/getify/You-Dont-Know-JS
- https://eloquentjavascript.net/
- https://codemyui.com/
- https://tevko.github.io/practice/
- https://every-layout.dev/
- https://htmlpreview.github.io/ This is one of my favourites, b/c I can quickly share htmls
- https://www.smashingmagazine.com/articles/
- https://rachelandrew.co.uk/archives/2020/04/07/making-things-better/
- https://ohhelloana.blog/ I love her blog, this is where I saw the bookmarks idea first!
- https://uigradients.com/#ColorsOfSky
- https://vineethtrv.github.io/loader/
- https://website-gallery.now.sh/
- https://medium.com/javascript-in-plain-english/creating-3d-layout-with-css-using-grid-perspective-65cd03dfc56c Her work looks really interesting! This is on my to-learn list
- https://codepen.io/collection/XzePLw

Starting to use a little bit of Javascript. Mostly to add a class to an element when clicked.

# 2020 September

Haven't been coding too much outside work lately. I've been reading this book "Thinking fast and slow" by Daniel Kahneman. Pretty good book so far, but I'm in the slow stretch right now haha! Trying to read at least half an hour everyday, which is like 10 pages for me, and I have 200 pages left, so hopefully I finish the book this month! 

Also, I've been cooking a fair amount of new food. Mostly Italian food, but I'm trying to semi-adopt the Meditarranean diet, which is basically eating tons of veggies, fish and less red meat. I encourage everyone to try it! It's a healthy principle without taking away too much fun :)

- https://www.interaction-design.org/literature/topics/gestalt-principles
- https://blog.datawrapper.de/weeklychart-logscale/
- https://lisacharlotterost.de/ Love this blog. So much practical tips!
- https://blog.datawrapper.de/beautifulcolors/
- https://medium.com/free-code-camp/we-fired-our-top-talent-best-decision-we-ever-made-4c0a99728fde This post was really cool. "Rick" is an interesting concept. Let's try not to be one, but the comment section is where the real discussion happens, so make sure to check it out!
- https://www.youtube.com/watch?v=C13JC_YP2Q8&feature=youtu.be - Linda is great. Her recommendation of the book "Thinking fast and slow" is what I'm reading right now.
- https://medium.economist.com/why-you-sometimes-need-to-break-the-rules-in-data-viz-4d8ece284919
- https://gabriellew.ee/

# 2021 April

Hey,  

I decided to start a dedicated diary section using #diary tag! With the blog posts, I like starting with a quick update on my personal life at the moment. Sometimes, I really want to write a little more than a couple sentences, but stop myself for the sake of keeping the post relevant to the topic. As someone who doesn't take too many pictures of anything, there are periods in my life that I have little recollection of what was going on at the time. So yea, I'm hoping to write regularly here (once a month? maybe more?), and look back at this tag later! 

I don't really have any specific format in mind, but this time, I sat down for a couple hours thinking/reflecting on life, wrote whatever came to mind, __left the desk__, came back, read what I said, and edited.

Listening to [the Marias](https://www.youtube.com/watch?v=fTJ0Pvt56aI) right now. I think I found these guys at the beginning of this year, and been in love with them! They hit the sweet spot for me, that nice mix between electronic groove and rock. Other artists I like at the moment: 53 Thieves, Men I Trust, John Mayer, CHVRCHES (throwback to 17-18 y/o me), 새소년 (blog plz render korean), Barrie, Chet Atkins.

I got promoted at work! Since March, I've been the "BI Advisor" at the same team. I still dig into problem solving, but I'm hoping to help facilitate in-depth data analytics collaboration between teams. 

Recently, I started using Twitter to follow data science people and it's a gem! Communities like [R4DS slack channel](https://www.rfordatasci.com/) and [Nick Wan's twitch streams](twitch.tv/nickwan_datasci) are exactly what I needed, because I don't have any real life friends in data science ! If you use R, I highly recommend hopping on slack! I'm in 2 weekly book clubs right now (advanced R & tidy modeling with R), and hoping to join another one soon! (Practical Statistics for Data Scientists) These not only keep your learning on track, but also help you work on presentation skills! :D

Speaking of Twitter, I've been doing the #TidyTuesday, where a bunch of people make cool visualizations using the weekly data by [r4ds](https://github.com/rfordatascience/tidytuesday). I love the works from [Georgios Karamanis](https://twitter.com/geokaramanis) and [Alexandra Bagaïni](https://twitter.com/a_bagaini). Also, I don't participate in this one but #30DayChartChallenge is really fun too! 

On a tad serious note, I do feel some lockdown/covid stress recently, the April lockdown really brings me down. I'm not cooking as much new things as I used to, and appetite is low. I'm around 145lbs nowadays. Really miss hanging out with friends after work at the Royal Oak, and kickboxing with training partners. I do my best to stay positive & active with running and bodyweight exercises, but it's been really tough to stay motivated. 

Kinda want to get a dog, am i responsible enough? we'll see

# 2021 May

Hiya, pretty uneventful month lol I did get vaxxed, so that's good! 

I'm getting more interested in making arts with ggplot. This means catching up in geometry, and some maths. I'm in need of a structure though. Right now, I just kinda learn whatever looks interesting to me, but it'd be nice to have a checklist of important concepts to learn. I do watch Coding Train on Youtube, which gives an idea of what's out there.

Norm Powell looks good on the Blazers.

Vanilla is a really good musician. 

- [A whole course on gen art??? But cest french](https://github.com/v3ga/Cours_Bordeaux_Montaigne/tree/master/L2_2020_2021)
- [Cool viz that I should do](https://blog.datawrapper.de/stacked-bar-chart-art/)
- [Cool generative art blog](https://generativeartistry.com/tutorials/)
- [Another cool gen. art blog](https://tholman.com/)
- [Book on Typography](https://practicaltypography.com/)
- [Cairo has a podcast](https://anchor.fm/ddjpodcast)
- [Magick masking](https://www.ddrive.no/post/miracles-with-magick-and-bunny/)
- [Magick colour extracting](https://www.rostrum.blog/2018/11/25/art-of-the-possible/)
- [Book on forecasting](https://otexts.com/fpp3/)
- [Resources on bayesian](https://github.com/rmcelreath/statrethinking_winter2019)
- [French keyboards](https://superuser.com/questions/743920/how-to-type-french-specific-characters-on-a-standard-us-keyboard-on-windows-usin)
- [Ottawa doggos](https://www.kiwisphotography.com/blog/2021/2/15/guide-to-ottawa-dog-rescues)
- [Brag your documentation](https://jvns.ca/blog/brag-documents/)
- [Colour Palettes](https://github.com/EmilHvitfeldt/r-color-palettes/blob/master/README.md#comprehensive-list-of-color-palettes-in-r)
- [Tufte Style Blog](http://motioninsocial.com/tufte/)
- [Cédric Scherer's ggplot guide](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/)

# 2021 June

Hiya, hope you're doing alright!

This month was pretty eventful! The corona situation looks certainly better than spring, and that means I can enjoy the summer! I still mainly stick to outdoors activities like golf and patios, but that's all I really need when the weather's good! All in for the roaring 20's

I'm fully invested in making generative arts with R. The more I do it, the more I fall in love with making it work. Right now, I'm just about to start the "Rainbow Smoke Bomb", so stay tuned :)

Lots of 80s pop

_Kinda_ cooking again

Working out again! My roommate's bought some weights

Overall, I've been in a great mood this month. Hope you are too. Bye!

- [Ideas and concepts on gen art](https://github.com/jasonwebb/morphogenesis-resources)
- [OpenProcessing](https://openprocessing.org/)
- [Shader Coding on Youtube](https://www.youtube.com/watch?v=2R7h76GoIJM&t=340s)
- [Apparently there are 17 types of tiling](https://en.wikipedia.org/wiki/Wallpaper_group)
- [I was super into tiling this month](https://en.wikipedia.org/wiki/Tessellation)
- [Really good math channel](https://www.youtube.com/watch?v=sMBeuEo9DvI)
- [Truchet tiles](https://www.youtube.com/watch?v=sMBeuEo9DvI)
- [Different use of . in R](https://stackoverflow.com/questions/54815607/r-combinations-with-dot-and-pipe-operator/54815713#54815713)
- [Big soccer guy](https://torvaney.github.io/)
- [NBA data news](https://thef5.substack.com/)
- [Penrose tiles](https://www.youtube.com/watch?v=ru9MrsHaGAk)
- [Control API pull rate](https://github.com/tarakc02/ratelimitr)
- [Smooth loops](https://necessarydisorder.wordpress.com/)
- [Emil's tips on purrr](https://www.hvitfeldt.me/blog/purrr-tips-and-tricks/)
- [Web scraping with R](https://colinfay.me/purrr-web-mining/)
- [Skew Normal Distribution](https://www.sciencedirect.com/science/article/pii/S0047259X11001126)
- [dplyr::all_equal()](https://sharla.party/post/comparing-two-dfs/)
- [This gen art blog looks sick](https://www.artnome.com/news/2018/3/29/ai-art-just-got-awesome)

# 2021 July

What's up y'all, it's a beautiful summer so far in Ontario, and it's been a great month again! I'm writing this in August, but cut me some slack - I'm on vacation! lol

I've been spending most of my productive free time doing the [#RecreationThursday](https://github.com/sharlagelfand/RecreationThursday) challenge on Twitter, and reading a bunch of R books (tmwr, advr, psfds, ...) 

Of course, every Tuesday, I've been following along with [#SLICED](https://www.notion.so/SLICED-Show-c7bd26356e3a42279e2dfbafb0480073) data science competition. Training the models actually eats up my shitty laptop, and most times, I'm not able to make a good submission within the 2 hour window. So I'm actually thinking about pulling the trigger on a Macbook with M1 chip.

They poured the foundation at the new place!

What else? 

- Golf. Tons of golf
- I should learn Bayesian statistics
- I'm trying to talk to more data science professionals to learn what's out there (so far talked to 1 lol)

Overall, really good few months lately. I'm really enjoying life

# 2021 Oct

Hey, it's been quite a while since I wrote one of these. 

I'm traveling to Germany in late November! Should be a nice change of pace. First time taking a long vacation since corona, so I'm really excited!

I've been reading a shit ton of R related contents. I really wanna get good at making packages and shiny apps. Also recently attended RinPharma, and saw a bunch of cool stuff! I don't know anything about this area, but lots of use cases for R there, and I think it's a good area to improve my R skills in.

I really made some good milestone on my [artwork!](https://twitter.com/jiwanheo/status/1452803930925174790) Printed and framed my flow field piece.

The past 3 months have been meh. Feel like I've just been going through the motion, stuck in the somewhat negative and stressed mental space, doing the same old stuff. I'm gonna turn this shit around.

I have a ton of bookmarks:

### Art

- [Generative Art blog](https://sighack.com/)
- [Perlin Noise](http://adrianb.io/2014/08/09/perlinnoise.html)
- [Perlin Noise](https://eev.ee/blog/2016/05/29/perlin-noise/)
- [Perlin Noise](https://blog.demofox.org/2021/04/11/perlin-noise-experiments/)
- [Collision Detection](https://ericleong.me/research/circle-line/)
- [Collision Detection](http://www.jeffreythompson.org/collision-detection/poly-point.php)
- [Dot Product](http://www.math.pitt.edu/~sparling/23021/23021vectorsand2dlines3/node10.html)
- [Tyler Hobbs Interview](https://www.youtube.com/watch?v=Bufm7VR4nfg)
- [Closest point to a line](https://diego.assencio.com/?index=ec3d5dfdfc0b6a0d147a656f0af332bd)
- [Closest point to a line](http://paulbourke.net/geometry/pointlineplane/)
- [Book on Grid](https://www.amazon.com/dp/3721201450)
- [Book recommendation](https://twitter.com/sableRaph/status/1427649830491496448)
- [Love this piece](https://twitter.com/samwise_v/status/1455958411766546440)

### ML/DS/Math

- [Feature Engineering book](https://bookdown.org/max/FES/)
- [Boosting algorithm](https://towardsdatascience.com/boosting-algorithms-explained-d38f56ef3f30)
- [Bayesian Optimization](https://www.tidymodels.org/learn/work/bayes-opt/)
- [Data Science project - Fantano Review](https://danielbrito.netlify.app/post/2021-07-24-fantano-doesn-t-like-to-dance-a-classification-model-on-needle-drop-s-reviews/)
- [Data Science project - Thom Yorke](https://www.thompsonanalytics.com/blog/thom-yorke/)
- [Interpretable ML](https://christophm.github.io/interpretable-ml-book/): definitely will revisit this book when I have to explain ML
- [Bayesian Resources](https://github.com/satrialoka/bayes-resources)
- [Intro to Bayesian](https://statswithr.github.io/book/)
- [Math Youtube Channel](https://www.youtube.com/watch?v=9vKqVkMQHKk&list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr&index=3)

### R/coding stuff

- [Shiny UI](https://unleash-shiny.rinterface.com/index.html)
- [plotly](https://plotly-r.com/)
- [Code Review](https://google.github.io/eng-practices/review/)
- [Efficient R programming](https://csgillespie.github.io/efficientR/)
- [Shannon's R packages](https://www.pipinghotdata.com/talks/2020-10-25-your-first-r-package-in-1-hour/)

### Bio/Medical(?) stuff

- [Medical Research](https://bookdown.org/pdr_higgins/rmrwr/)
- [Dezi's research](https://www.frontiersin.org/articles/10.3389/fncel.2020.00245/full)
- [Data Professor](https://www.youtube.com/watch?v=jBlTQjcKuaY&t=482s)
- [t-SNE Paper Dezi recommended](https://www.nature.com/articles/s41467-019-13056-x)
- [R Course on gene expression](https://www.udemy.com/course/differential-gene-expression-analysis/)
- [GeneTonic](http://shiny.imbei.uni-mainz.de:3838/GeneTonic/)
- [R Consortium](https://www.r-consortium.org/webinars)

### Misc

- [Cool blog](https://jingyis-blog.webflow.io/)
- [Data viz podcast I've been meaning to listen to](https://dataviztoday.com/shownotes/65)
- [Another podcast I've been meaning to listen to](https://anchor.fm/open-source-sports/episodes/Grinding-the-Mocks-with-Benjamin-Robinson-e16bu97)
- [Econ Course](https://github.com/uo-ec607/lectures)
- [Procrastination](http://www.structuredprocrastination.com/)
- [Side Hustle](https://www.linkedin.com/learning/side-hustle-strategies-for-data-science-and-analytics-experts)

# 2021 Nov

Hey! So I just came back from a 2 week vacation from Germany! (writing this on 2021-12-09) I guess it's really the first time since I started working full time that I took a proper vacation, and it was fucking great. Berlin was amazing. More than anything, I stepped out of my comfort zone, and tried to talk to as many people as I could. I sat at the bar counters, talking to random people, and so on. Never thought I had it in me lol

On my way back, Air Portugal messed up hard, and I was stuck in MTL for another day, which costed me another day of vacation :( but I made some friends, and got invited to come surf in Portugal (which I will take up on, Joseph!)

Anyways, that was a much needed break, and now I'm recharged to continue my quest to learn package/shiny dev and drug discovery.

### API Package Building Stuff

- [Lots of resources](https://towardsdatascience.com/creating-r-packages-what-you-need-to-know-2a20233b328a)
- [Hadley's guide](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html)
- [Colin's guide](https://colinfay.me/build-api-wrapper-package-r/)
- [Basics to API](https://zapier.com/learn/apis/chapter-1-introduction-to-apis/)
- [Julia's Travis guide](https://juliasilge.com/blog/beginners-guide-to-travis/)
- [Dean's guide to R environment](https://daattali.gitbooks.io/stat545-ubc-github-io/content/bit003_api-key-env-var.html)
- [Guide to commit messages](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)

# 2021 Dec

Alright, what did I do in 2021

- Travelled to Berlin before Omicron 
- Dabbled into rtistry, wrote a couple blog posts
- Wrote my first R package, rBreakingBad
- Am working on my first {golem} shiny app, {senTWEETment}
- Did some r4ds bookclubs (advr, tmwr) - TY all!
- Re-did my blog theme
- Tons of golf with my family!
- Actually gave birthday presents to my friends
- Shaved my head
- Got promoted at work
- Got boosted
- Finally on Spotify
- Man. that trip affected me HARD. I wanna live in Europe

Goals for 2022 (right now): 
- See the world
- I really want to work with R coders. Love me some shiny apps & package dev
- I want to use my skillsets in a meaningful way (that I'm proud of!)
- Write about some unfamilliar rtistry concepts!